### ISSUE TITLE
Update Change Wallet screens [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1081]
Sketch Cloud:
https://sketch.cloud/s/jDODG/a/O45Lnk
https://sketch.cloud/s/jDODG/a/AMqj0r
https://sketch.cloud/s/jDODG/a/mndzOg

Zeplin:
(app link) zpl://screen?sid=5e21dbe3b8a95e2b2a9e6838&pid=5d088205bff2d15de6a4397b
https://zpl.io/adGApxL
https://zpl.io/2915OqA
https://zpl.io/boNkD1g

- Display ENS reverse lookup if they correspond directly to ETH address
- Display Blockies
- Display balance
- Display ENS reverse lookup | address in a format 0x, four characters, ellipsis, four last characters

**Comment by tomekalphawallet** [comment]
![change_wallet](https://user-images.githubusercontent.com/51817359/72661521-60085000-39db-11ea-9683-7e8aae242c0b.png)

**Comment by justindg** [comment]
@tomekalphawallet how do I go from **Change / Add Wallet** to **Manage Wallet** screen?

**Comment by JamesSmartCell** [comment]
The expected event when I click on the wallet in this screen is to select it. I couldn't see how to get to the manage screen - it shouldn't happen when you click on the bar because there's a radio button.

@justindg Suggestion - if you click on the blocky/gravatar it should take you to the manage wallet page. @tomekalphawallet can you confirm if this is the intention?

**Comment by tomekalphawallet** [comment]
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e21dbe3b8a95e2b2a9e6838/

Added a hamburger menu on the right side. This way you can access Manage Wallet Page. 

@justindg

**Comment by justindg** [comment]
@tomekalphawallet noted, thank you!

**Comment by JamesSmartCell** [comment]
closed in #1242
