### ISSUE TITLE
new wallet created despite cancelling

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1145]
1. Go to "Chang Wallet"
2. Add a new wallet
3. Hit Cancel

Result: The wallet is already created;

Expected: if you cancel it, the wallet isn't created.

This is imporant as users like to go over options to see which one suits their needs and didn't intend consequence in exploration.

**Comment by JamesSmartCell** [comment]
When you clicked on the '+ create a new wallet' text the app followed your instruction and created a new wallet.

Should there be an intermediate screen here which is a 'please confirm wallet creation'? If so, then it should be designed into the UX flow as an extra screen.

Be careful changing anything here - if user clicks 'create a new wallet' then they probably expect a new wallet to be created at that stage. If back is clicked and the wallet is gone because save wasn't pressed that is worse.

**Comment by colourful-land** [comment]
This is incorporated in fiji so not tracked seperately by issues.
