### ISSUE TITLE
TokenScript Management page

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1246]
Currently there are 3 directories for TokenScripts (2 for Android 10+).

The primary area is in the private app area buried at /data/data/io.stormbird.wallet/files. The files here are Scripts sourced only from the repo and will all be signed, official scripts.

The secondary areas are 'overrides'. 

The second directory is the External directory at /Android/data/io.stormbird.wallet/files which can be seen and used from any file explorer. If you click on a script intent and pick alphawallet this is where the script will be written. If a script placed here clashes with a script in the primary area the script in this directory will override it.

The final directory is the 'legacy' script directory which can no longer be used on Android 10+. This is at /AlphaWallet. Developers can simply drag/drop their scripts into this directory. Any script placed here overrides scripts in both the External directory and primary area.

This page should allow devs and users to see what scripts are overriding. 
The screen shouldn't distinguish between External and Legacy directory.
This screen is currently a placeholder as no spec is published. In iOS this screen is a simple text listview which lists the name of the scripts that are in the secondary directories. Clicking on one of the text items brings up a share page.

Place this page in the 'Advanced' area in settings. When you click on an item you should be able to share or delete it.

You may need to add a fetcher method to AssetDefinitionService to fetch the overriden scripts.

TODO: page should also allow you to switch between using override and primary scripts, although this is less important.

**Comment by JamesSmartCell** [comment]
@hboon @colourful-land @James-Sangalli Please add any further details for TokenScript management page as required.

**Comment by hboon** [comment]
The iOS screen was added a long time ago largely due to platform constraints. AirDrop was the primary way to override TokenScript files and there was no way for the user to open a File Manager to look at the list of overridden TokenScript files, as well as to remove them.

So this particular screen doesn't necessarily have to be exactly the same as iOS'. The Android version has the potential to be more useful.

An example which I guess doesn't add too much to the scope:

Would it be useful for the Android app to have a single button to bring up a file manager app showing the appropriate (external or legacy) directory so the users can both manage the files there and discover where it is?

But to implement that, it might be helpful to automatically move all the files from legacy directory to external directory for Android 10+? Then only 1 directory is used for overrides.

---

There are more fancy things that could be useful on both platforms in the future, like providing a way to list which contracts a TokenScript applies to, whether it is signed and the signature valid. Whether there is a conflict etc. But if we do these, it's probably good to scope and design it in more details.

**Comment by JamesSmartCell** [comment]
> Would it be useful for the Android app to have a single button to bring up a file manager app showing the appropriate (external or legacy) directory so the users can both manage the files there and discover where it is?

Yes.

> But to implement that, it might be helpful to automatically move all the files from legacy directory to external directory for Android 10+? Then only 1 directory is used for overrides.

Yes, it would be good to standardise and lose that directory while we're the only ones using it.

> There are more fancy things that could be useful on both platforms in the future, like providing a way to list which contracts a TokenScript applies to, whether it is signed and the signature valid. Whether there is a conflict etc. But if we do these, it's probably good to scope and design it in more details.

I started a page in the tokenscript forum here:

https://community.tokenscript.org/t/tokenscript-managment/348

It would be useful to have issue reporting with scripts, within the app. We do have a command line tool that I will add error and warning feedback to.

**Comment by JamesSmartCell** [comment]
This has been added.
