### ISSUE TITLE
Make gas price adjustment more obvious

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1437]
Recently we got a 1* review because someone didn't like the suggested gas price (over 30 gwei, during 100% ethereum loading) and didn't know/weren't aware gas price is decided by supply/demand loading not by the wallet.

Also they didn't know you could adjust the gas price.

Could we make it more obvious that the gas price can be adjusted on the confirmation screen? When someone's looking at the gas price that's where their focus is, maybe something could be put there.

**Comment by hboon** [comment]
@JamesSmartCell Remember we have a yet-to-implement action sheet-style UI replacement for confirmation screens. That would help https://zpl.io/aNJ6Ykv

**Comment by JamesSmartCell** [comment]
@hboon I'm not allowed to see that page :(

**Comment by hboon** [comment]
@JamesSmartCell I see a similar one for Android in https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e996534a4a77b53a3c35ef0

But it looks like it's not in-sync, the iOS version has the gas displayed. @tomekalphawallet would you help to grant James access?

<img width="408" alt="Screenshot 2020-05-29 at 4 45 33 PM" src="https://user-images.githubusercontent.com/56189/83240338-d3ad3b80-a1cb-11ea-8d4f-13fcf4058611.png">

I was building the iOS version halfway a few months ago and unfortunately had to shelve it to work on other things. But I think it helps to resolve this GitHub issue or at least we can tweak it to solve it rather than to work on the existing confirmation page unless it's a tiny change

**Comment by tomekalphawallet** [comment]
> @hboon I'm not allowed to see that page :(

You are now.

**Comment by tomekalphawallet** [comment]
What if:

By default, we use a recommended speed. When the action sheet is extended, they can set up manually. If they change their mind, the toggle can set it back to the recommended speed. 

<img width="1683" alt="Screenshot 2020-05-29 12 18 10" src="https://user-images.githubusercontent.com/51817359/83249182-7c48a480-a1a6-11ea-9bb5-ca3083cfc7a1.png">

**Comment by hboon** [comment]
@tomekalphawallet That’s the current design of the actionsheet right?

I think in this case, the recommended gas is too much (to the user especially because it can fail). So a possible improvement is to hardcoded a heuristic and display a warning of some sort when gas amount > $X or X ETH

What do you think?

**Comment by JamesSmartCell** [comment]
I like it - but I think we should err on the side of recommending a lower gas price unless the user requires the transaction to parse quickly. Maybe something like a 'Turbo' (or the 21st century equivalent 'Warp') button that is expensive but the user has to click it to get a < 10 mins or <1 min.
