### ISSUE TITLE
when user is on ropstern, the ETA is taken from mainnet

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1490]
When I am on ropstern, the with the default gas it showed around 300 mins ETA.

So I clicked OK anyway thinking I can wait 5 hours.

Then it gets included in the blockchain in 1 minute.

This hint that perhaps the ETA is taken from the mainnet, not the current (ropstern)

recommend: If you don't have a reliable ETA for ropstern, make ETA go away except for the chains you have ETA.

**Comment by JamesSmartCell** [comment]
This is correct. The API we're using only has stats for mainnet. I figured it wasn't a high priority since it only affects testnets. It will also affect iOS, although I don't think iOS has implemented this API yet.

Currently there's no way to solve this one, other than guessing. Therefore it's not a good candidate for an assigned fix unless someone wants to write a guessing heuristic for each of the test nets. Metamask does the same thing last time I checked - use mainnet API guess for tx time.

**Comment by colourful-land** [comment]
> Or, just remove the guess time for all the testnets.

That's what I proposed there at the beginning of the issue. By doing so, does it help to reduce the difference between forks and ours (where forks default to a net that is different than mainnet so we automatically not provide ETA)?

**Comment by colourful-land** [comment]
> I figured it wasn't a high priority since it only affects testnets.

And every net that is not mainnet - e.g. Nervos

**Comment by JamesSmartCell** [comment]
> > Or, just remove the guess time for all the testnets.
> 
> That's what I proposed there at the beginning of the issue. By doing so, does it help to reduce the difference between forks and ours (where forks default to a net that is different than mainnet so we automatically not provide ETA)?

Let's do this as a quick fix then - don't display any time estimate just use 'slower' and 'qucker'.
