### ISSUE TITLE
αW not protecting the wallet recovery user entry screen

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1514]
~~1. When the user enters backup-activity, he gets a message explaining what's seed phrase / keystore json. at which point he can't take a screenshot or make video recording. This screen *should not* be protected (the one after it should)~~ (removed as Chintan raised a question on this and I prefer to progress the next item without addressing it)

2. When the user recover from a backup, he types json keystore and this screen can be video recorded - where it *should* be protected.

**Comment by ChintanRathod** [comment]
@colourful-land 
I check the code and found that "BackupKeyActivity" has global SECURE_FLAG enabled. It has different backup states it passes through. So regardless of state, it will protect the user from taking picture or recording. 
Question: Should this behave state of backup process wise?

**Comment by colourful-land** [comment]
>  Question: Should this behave state of backup process wise?

I don't understand the question

**Comment by JamesSmartCell** [comment]
@colourful-land As it stands you can't record or photograph any part of the backup key activity. Changing this behaviour is very dangerous.

**Comment by JamesSmartCell** [comment]
@ChintanRathod I discussed this with Weiwu can you update the PR so that:

- The initial backup screen, which is either the 'Back up your wallet with seed phrase' or 'What is Keystore JSON?' is a separate, tiny activity which can be photgraphed.
- On clicking the 'Back up my wallet' or 'Export Keystore JSON' button you are taken to the BackupKeyActivity which has the 'SECURE_FLAG' set.

This way there's no possibility that anything can go wrong.

**Comment by ChintanRathod** [comment]
@JamesSmartCell OK. Understood and I will do it.
