### ISSUE TITLE
Gas Limit shouldn't be in GWEI

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1539]
Currently gas limit is in GWEI, it is true only if gas price is 1

**Comment by AW-STJ** [comment]
To add further clarity remove GWEI in the two instances highlighted:
![image](https://user-images.githubusercontent.com/61957841/88987856-99bafb80-d31a-11ea-9126-b800a4254068.png).

**Comment by JamesSmartCell** [comment]
@ChintanRathod I think this is already done in the master branch, but needs to be replicated in the Activity-Refactor branch.

Since master has diverged from Activity-Refactor branch we will be force pushing Activity-Refactor over the master branch, and will adapt any mods to master independently to avoid creating issues. EG reflecting the issue with rejected transactions has to be handled differently between the two branches as the underlying code changed.

**Comment by ChintanRathod** [comment]
@JamesSmartCell We can close this issue as it is merged to Master branch already. No need to do any extra work on this. 
Commit hash bcb37ee033952917a92e56edbb18a9d4dd4a05e9
