### ISSUE TITLE
How to change the default link of Dapp Browser?

### ISSUE THREAD

**Issue by wolfenix** [AlphaWallet/alpha-wallet-android#1625]
Hi, I want to change the default url of the browser tab to my website, how should i do it, Which java file should i edit, I'm kinda noob :).

**Comment by JamesSmartCell** [comment]
Hi @wolfenix sorry about not answering you! 

I hope you already worked it out, but the default website is on the setting 'DEFAULT_HOMEPAGE' in class EthereumNetworkBase.

If you do a wallet build, the most important thing is to add your own Infura key in the build.gradle file, look for this string:

DEFAULT_INFURA_API_KEY

the API key we bundle in the repo is a 'throwaway' key that's used by anyone else building the wallet, just so that it will kind-of work. You can create your own Infura key for free on the Infura website, then the wallet will work a bit better.

**Comment by Codahuy** [comment]
DEFAULT_HOMEPAGE is not in the EthereumNetworkBase anymore?
