### ISSUE TITLE
How to add my token in code?

### ISSUE THREAD

**Issue by wolfenix** [AlphaWallet/alpha-wallet-android#1626]
Hi, I need to add my own ERC20 token by default in the code so whenever somebody installs the app, the token will show below the ethereum already added.

plz tell me the way.

**Comment by mercuzzi** [comment]
i am also interested in this, let me know if you make any progess

**Comment by JamesSmartCell** [comment]
Hi @wolfenix and @mercuzzi . It's very easy to add your tokens. Look up this file:

known_contracts.json

In the app/assets directory.

Simply add your token following the convention in the file like this:

```{"address": "0x1234567879124565384752389aBcDeF000", "name": "MYTOK",   "isPopular": true, "network": 1},```

Note that if you want to have a funky icon for your token you should submit a PR to this repo (not owned by us):

https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets

Alternatively if your token is on a testnet you can submit an image to our repo here:

https://github.com/AlphaWallet/iconassets

We will expand the scope of this repo as a 'catch' so that if a token icon isn't found in the TrustWallet asset repo, if the address matches with one in our repo we'll use that icon.

**Comment by mercuzzi** [comment]
hi James, yes I figured it out thank you sir.

I've gotten my version of it released on the Google Play Store as Pureon Wallet. When a user exchanges for the PUR token it will add my custom ERC-20. 

https://play.google.com/store/apps/details?id=com.pureon.pur_wallet
Note: Pictures are from old application

How would I implement the changes you guys are making since ive forked it? 

Cheers!

**Comment by Codahuy** [comment]
> hi James, yes I figured it out thank you sir.
> 
> I've gotten my version of it released on the Google Play Store as Pureon Wallet. When a user exchanges for the PUR token it will add my custom ERC-20.
> 
> https://play.google.com/store/apps/details?id=com.pureon.pur_wallet
> Note: Pictures are from old application
> 
> How would I implement the changes you guys are making since ive forked it?
> 
> Cheers!

Hey mercuzzi!
I saw your app in google play.
How did you removed some features from the original repo? 
Thanks

**Comment by ManeeshNadcab** [comment]
how to change RPC i want add my RPC as default and also my token

**Comment by ManeeshNadcab** [comment]
please help guys please

**Comment by ManeeshNadcab** [comment]
i am in trouble from 3 days
