### ISSUE TITLE
USDT is not in the popular token list?

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1661]
|  USDT is not in the popular token list | and takes a very long time to show up in the wallet. |
|---|---|
| ![imagen](https://user-images.githubusercontent.com/548435/97935062-9e84c500-1dcb-11eb-8817-78c46e6a705f.png)  |   |

**Comment by AW-STJ** [comment]
One for you when you have some time.

Add USDT to the tokenlist of popular tokens. Contract address: 0xdac17f958d2ee523a2206206994597c13d831ec7

For more information https://www.coingecko.com/en/coins/tether

**Comment by JamesSmartCell** [comment]
USDT is in the popular list:

{"address": "0xdAC17F958D2ee523a2206206994597C13D831ec7", "name": "USDT",   "isPopular": true, "network": 1},

Somehow it's been added twice which is a bug: line 12 and line 77.

This issue is actually in the filter and is baked in with the implementation method.

Currently the implementation is that we smoothly discover the tokens when the wallet is created, sequentially. This issue is most likely caused by the user attempting to search the token list seconds after creating the new wallet.

Here's how I would advise solving:

1. Populate the token filter list with the 'skeleton' information contained within the known_contract.json list.
2. Continue to resolve the detailed information as currently in the implementation. 

When the user types the name, search the current list we have (at first we only have symbols eg USDS, USDT etc so the search needs to include symbol as well as name).
