### ISSUE TITLE
Implement deep links for Fiat-on-Ramp on Ramp.network

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1738]
Let us extend the fiat-on-ramp functionality to all the tokens available on Ramp network.

**Comment by AW-STJ** [comment]
The current implementation takes users to Buy ETH for DAI, USDT etc.

Let us make the Buy <token> button for:
- USDC
- USDT
- DAI

**Comment by JamesSmartCell** [comment]
Hi @justindg If you implement this it should be done in a generic way - if you extend the current way it will lead to a mess.

Suggest you create an XML file with a list of contracts that are supported by Ramp eg
0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,USDC
0x6b175474e89094c44da98b954eedeac495271d0f,DAI
0xdac17f958d2ee523a2206206994597c13d831ec7,USDT

Then, add a feature (within FunctionButtonBar is ok) to scan this file and add a 'Buy xxx with Ramp'.
Then patch the rest of the code to handle this generic system. After that it'll be easy to add more tokens as they become available.

As an extension can you add the site definition eg

0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,USDC,Ramp
0x6b175474e89094c44da98b954eedeac495271d0f,DAI,Ramp
0xdac17f958d2ee523a2206206994597c13d831ec7,USDT,Ramp

And then generate the URI intent based on which Fiat on-ramp supplies that token, so that in future we can add new tokens with different on-ramp.

**Comment by JamesSmartCell** [comment]
Close completed issue
