### ISSUE TITLE
Add 'Import Wallet' above the keyboard after you enter 12th phrase

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1743]
The problem I found during [user test](https://drive.google.com/file/d/12IointWFw3vauswvia-Fz8noViM2VzS7/view?usp=sharing) is that after entering the 12th phrase you have to hide the keyboard to reveal the "Import Wallet" button.

Therefore, I suggest displaying the "Import Wallet" button right after you enter the 12th phrase. 

Zeplin:
11th phrase https://zpl.io/29pk04e
12th phrase https://zpl.io/bP6zjqM

Currently:
<img width="981" alt="Screenshot 2021-02-24 at 10 04 41" src="https://user-images.githubusercontent.com/51817359/108976382-bdafa700-7687-11eb-81ba-81b02a2e3018.png">

Should be:
<img width="1147" alt="Screenshot 2021-02-24 at 09 54 02" src="https://user-images.githubusercontent.com/51817359/108976412-c56f4b80-7687-11eb-98b9-2608c65f846b.png">

**Comment by JamesSmartCell** [comment]
The original reason this button was hidden is because it crunched up the screen too much when the keyboard is present on certain phones, this issue may have gone away now with those phones being phased out. 

A more complete fix would be to:

1. Ensure IME button is working correctly (in your picture it's the CR symbol in the bottom right next to the '.' button: before having 12 words, IME should be blank or the default return as in the picture above, after 12 words it changes to a tick.
2. Detect screen pixel height, if below 1024 then don't display the button.

**Comment by colourfreak** [comment]
> The original reason this button was hidden is that it crunched up the screen too much when the keyboard is present on certain phones, this issue may have gone away now with those phones being phased out.

Yes, you are right. I am aware of this. For this reason, I am designing for the smallest viewport size possible (360x640). All other phones have larger sizes and they are usually 2x or 3x. But even if you divide their viewport sizes by 2 or 3 you will find this the smallest.

https://yesviz.com/viewport/
