### ISSUE TITLE
Send address populated incorrectly for ERC20 tokens on xDAI

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1779]
I had this user complaint the other day, where she was claiming that her HNY transaction were failing. I tested and was not able to find the root cause.

But today I found out the issue, in the current Playstore version [3.24.4(145)].

Steps to replicate:
- Select a ERC20 token on xDAI network such as HNY, COIN etc.
- Copy/paste an address to send xDAI to and proceed
- In the confirmation screen, you can see that the receiver's address is now changed to the token's contract address

Bug Video: https://drive.google.com/file/d/1gYnaq2sqzdeclFe_zboia9Ae3sG8EAwN/view?usp=sharing

**Comment by JamesSmartCell** [comment]
This may also have been reported to me from the Artis crew. I'm going to see if it's the same issue.

**Comment by JamesSmartCell** [comment]
Luckily the bug is cosmetic only, if you actually did send the funds they'd go to the correct destination, so it's not urgent.

@ChintanRathod this is caused by taking the transaction destination rather than the destination set in the previous screen.

Recommend you add an extra param to the ActionSheetDialog constructor, and pass the destination address as specified by the AddressInput widget (in addition to the ENS name, if present). 

EG if I type: vitalik.eth as address then in ActionSheetDialog I will have destName="vitalik.eth" and eg destAddr="0xd8da6bf..."

then pass those two on to the place where address is setup.

You'll have to do this everywhere where that constructor is called, it's always from a place with an AddressInput so it should be ok.

**Comment by JamesSmartCell** [comment]
I can fix this, requires a re-release.
