### ISSUE TITLE
WalletConnect scanning QR code does not work

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1811]
Looks like this issue has surfaced up on both iOS and Android platforms. 

After scanning the app (tried on OpenSea and UniSwap) the WalletConnect goes to the loading screen where remains stuck The approval does not happen. In one instance on Android, I got the approve screen but nothing happened after approving. The WalletConnect never got to 'Approve' screen after that.

![image](https://user-images.githubusercontent.com/61957841/115129010-60035f80-a025-11eb-8e82-7d2b2fb818ee.png)

**Comment by JamesSmartCell** [comment]
@AW-STJ works correctly for me on walletconnect example, Uniswap and Opensea.

Let's try to narrow down what circumstances it fails and how to refine: I have witnessed flaky connection behaviour previously which I fixed by disconnecting WC, reload the site and try again. We should try to do some of these things automatically if it could help.

Also - I have had issues while trying to use WC over VPN. I'm not sure if we could fix this but it seems important to try. Can you check again now, do you use VPN?

**Comment by AW-STJ** [comment]
Works now. And I do not use VPN and my WiFi had not issues at the time. I discovered the issue when a user reported it. 

So it could be an issue from WalletConnect's side that was fixed.
