### ISSUE TITLE
Allow users to add networks through Custom RPC

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1822]
We have been getting a couple of feature requests from our users as well as during user interviews. Also, it makes sense to allow this, as the number of EVM networks out there is increasing day by day. We often add them to our growing list of supported networks. Why don't allow users to do it own their own?

@colourfreak - can we get the designs for this?

Here is how Metamask goes about it:
![image](https://user-images.githubusercontent.com/61957841/116332894-eaae4080-a815-11eb-8a14-f9bb944dd74a.png)

**Comment by hboon** [comment]
Which networks are users asking for that aren't supported? Are those testnets, in particular? Because there is a list of chains out there [1] and we might do better to just let the user choose from the list or use the list for autocompletion. The list wouldn't include private testnet or un-launched mainnets of course. But it might make the feature a whole lot better.

We might still want to provide the functionality for users to type them in themselves of course, but if we know what is the problem the user is trying to solve here, we might design something better [2].

[1] https://github.com/ethereum-lists/chains
[2] Some parallels with the add custom token screen which we inherited but haven't improved since

**Comment by JamesSmartCell** [comment]
Yes, I was planning to do this via https://github.com/ethereum-lists/chains, but also allow users to add data; eg if ethereum-lists doesn't have the Etherscan API, users can add that in, in the settings page. Either way, there should be a page that looks like the one that you added from MetaMask.
