### ISSUE TITLE
Error while Launching activity

### ISSUE THREAD

**Issue by trustwalletvn** [AlphaWallet/alpha-wallet-android#1975]
Hello
I'm build wallet it show error
By the way how to translate and add new language add Fiat currency  ?
Thank you!

adb shell am start -n "com.alphawallet.app/com.alphawallet.app.ui.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.alphawallet.app/com.alphawallet.app.ui.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.alphawallet.app/.ui.SplashActivity }
Error type 3
Error: Activity class {com.alphawallet.app/com.alphawallet.app.ui.SplashActivity} does not exist.

Error while Launching activity

**Comment by JamesSmartCell** [comment]
Hi @trustwalletvn, can you try building and running with AndroidStudio? I suspect you have an error in your starting line; adb probably doesn't work in this way as the .apk file knows the entry point.

To add a new language and currency:

Currency: 
- Add the SVG flag to drawable (so that it's called eg ic_flags_vietnam.xml).
- Add the currency eg like this: ```new CurrencyItem("VND", "Vietnamese đồng", "₫", R.drawable.ic_flags_vietnam),``` in ```CurrencyRepository```.

Language:
- See these two commits which added French: https://github.com/AlphaWallet/alpha-wallet-android/commit/d89363c96499c11b4d1c7fdc40b7a7bd1798858d and https://github.com/AlphaWallet/alpha-wallet-android/commit/1e37c0b14dbce2e2195a8e3ee9c75ba3733f656b

The default language of the app is determined by the phone; so if you added Vietnamese language and the installer's phone is set to Vietnam locale, then the app defaults to Vietnamese.

To force currency default change the relevant parts of these lines:

```
class TickerService
...

    private void initCurrency()
    {
        SharedPreferences pref = PreferenceManager.getDefaultSharedPreferences(context);
        currentCurrencySymbolTxt = pref.getString("currency_locale", "USD");
        currentCurrencySymbol = pref.getString("currency_symbol", "$");
    }
```



```
class C
...
   public static final String DEFAULT_CURRENCY_CODE = "USD";
```

If you add Vietnamese language would you be able to share it with us :) submitting a PR to our repo we would be really grateful.

PS here is a sample SVG for Vietnam flag from our implementation database, in the expected format:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="40px" height="40px" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>38B61D99-CA86-4F91-ADE2-6F1FCC4046C5</title>
    <g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Icons/Flags/vietnam" fill-rule="nonzero">
            <g id="vietnam">
                <circle id="Oval" fill="#D80027" cx="20" cy="20" r="20"></circle>
                <polygon id="Path" fill="#FFDA44" points="20 10.4347656 22.1584375 17.0776563 29.1432031 17.0776563 23.4923437 21.183125 25.6507813 27.8260938 20 23.7205469 14.3492188 27.8260938 16.5076563 21.183125 10.856875 17.0776563 17.8415625 17.0776563"></polygon>
            </g>
        </g>
    </g>
</svg>
```

**Comment by trustwalletvn** [comment]
I can translate to Vietnamese
Copy this file from
https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/values/strings.xml
and create new folder "values-vi" put file strings.xml
translate it and submit commits?
is it true?

**Comment by JamesSmartCell** [comment]
> I can translate to Vietnamese
> Copy this file from
> https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/values/strings.xml
> and create new folder "values-vi" put file strings.xml
> translate it and submit commits?
> is it true?

Yes, that's it. The Android SDK will do the rest (including fetching the localised names for each language in the ```class SelectLocaleActivity```). Don't forget to add 'vi' to the LOCALES list in ```LocaleRepository```.

**Comment by trustwalletvn** [comment]
Thank you.
Take a few day to completed translate

**Comment by JamesSmartCell** [comment]
Looking good so far - just need to add a flag, the currency entry for VND and the LOCALE entry.

**Comment by JamesSmartCell** [comment]
Hi @trustwalletvn I collected your PR's into one big PR and merged it. The Vietnamese support will be in the next release. Can you do a pull on your wallet fork to get the latest work?

**Comment by JamesSmartCell** [comment]
Hi @trustwalletvn the new localisation is live in the PlayStore and on the direct download on our site.

Thank you again for creating this localisation. We'll try to maintain it, but we don't have any Vietnamese speakers in our team, so we'll try using Google Translate to create the new text.

Feel free to ping us if you have any new ideas/collaborations. Remember to keep your fork up to date, we just had a big update which is working well and there's a new UI overhaul coming soon which is another big improvement.
