### ISSUE TITLE
Updated icons to iconssets do not update after 3 months

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1986]
How much longer do we have to wait until someone will start to care about this product?

**Comment by AW-STJ** [comment]
Are you referring to a specific open issue? 

Or if its a rhetorical question, I completely agree that Android has not had the love that it deserves for a while. As you know we are definitely under the pump with AutographNFT, Devcon, and other projects that is going on but we will get AlphaWallet Android app attended to and well groomed very soon.

**Comment by JamesSmartCell** [comment]
Firstly - I take umbrage over the assertion that this project hasn't had any care or love it deserves even lately. A lot of time and care have been taken over the past months on ERC1155 alone to get it working correctly with full attention to detail.

@colourfreak check the work on the repo, it speaks for itself. Some refactors were required in order to correctly support ERC1155, the draft of which is pending review. In order for the app to have some love, it needs to be supported from all sides not just from the development side (which along with your UX work is the only two places where it is looked after). The UX design is focussed on iOS because our our company almost exclusively uses iOS mobile and that's how things are - Android is always going to be second fiddle here.

Samoa support is in progress and due to complete shortly as most of the assets are in place, it needs the infrastructure to be hooked up.

On a related note perhaps no-one has looked at the ERC1155 draft posted several days ago. FYI it's the culmination of over two months of development work, the wallet implementation was non trivial as 1155 is a bit of a mess - the major users of ERC1155 have interpreted the spec differently or done their own spin on it, and a lot of data is stored off chain with no hooks to it (eg collections). This is understandable, as it's kind of user curation.

**Comment by colourfreak** [comment]
How about iconssets not updating?

**Comment by zhangzhongnan928** [comment]
moved to internal discussion
