### ISSUE TITLE
Transaction confirmation actionsheet in landscape mode should scrollable to reveal all the content

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2167]
<img width='200' src='https://user-images.githubusercontent.com/56189/138201016-17d1cc9f-c8a7-4cf6-b821-5d522d5c7951.png'>

In the screenshot, the `amount` at the bottom can't be scrolled into the viewport

**Comment by JamesSmartCell** [comment]
Hi @mpaschenko can you create a landscape layout for the TX view and use as appropriate. You'll have to regenerate the view if the user swaps landscape to portrait too; since the ActionSheetDialog is always a member it shouldn't need too much surgery.

In the Landscape view just space out the text so it occupies less width, maybe put everything on a single line that can wrap around (with the different text styles you'll have to use a Styleable text string with the text style directives). For the chain icon, to reduce height you can use the new ```TokenIcon``` method ```setChainIcon``` which will be replacing most of the ```ChainName``` instances.
