### ISSUE TITLE
Make WalletConnect signature request be clearer about where it's coming from #3289

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2228]
Refer https://github.com/AlphaWallet/alpha-wallet-ios/issues/3289#issuecomment-953465632

**Comment by JamesSmartCell** [comment]
I like the use of the ActionSheet dialog to confirm the WC connection. I'll modify Android accordingly. And add the extra info,

**Comment by JamesSmartCell** [comment]
@asif-finimble can you route the approve session dialog through ActionSheetDialog instead of AlertDialog popup (see the AlertDialog in `onSessionRequest`).

Maybe you can create a 'WalletConnectInfoWidget' class similar to the other widgets which form the `ActionSheetDialog`, which holds all the info shown in the ios issue linked above. For reference see the basic `ActionSheetDialog` invocation for a message, from `DappBrowserFragment`. The only dynamic part of this would be the 'change chain' button in the chain display. To implement that you'll need a callback from your widget to an `ActivityResultLauncher` for the chain select (see `getNetwork`) and catch the result, update the ActionSheet, update the client object in `WalletConnectionService` and proceed as per the remainder of Approve in `onSessionRequest`.

Note that, if user cancels the connection, they would simply drag the ActionSheetDialog out, or click outside of it. That triggers the `dismissed` callback function so you'll need to hook that up accordingly. If they click 'Approve' then you can go through the 'buttonclick' callback, or create a new callback route.

**Comment by asif-finimble** [comment]
> @asif-finimble can you route the approve session dialog through ActionSheetDialog instead of AlertDialog popup (see the AlertDialog in `onSessionRequest`).
> 
> Maybe you can create a 'WalletConnectInfoWidget' class similar to the other widgets which form the `ActionSheetDialog`, which holds all the info shown in the ios issue linked above. For reference see the basic `ActionSheetDialog` invocation for a message, from `DappBrowserFragment`. The only dynamic part of this would be the 'change chain' button in the chain display. To implement that you'll need a callback from your widget to an `ActivityResultLauncher` for the chain select (see `getNetwork`) and catch the result, update the ActionSheet, update the client object in `WalletConnectionService` and proceed as per the remainder of Approve in `onSessionRequest`.
> 
> Note that, if user cancels the connection, they would simply drag the ActionSheetDialog out, or click outside of it. That triggers the `dismissed` callback function so you'll need to hook that up accordingly. If they click 'Approve' then you can go through the 'buttonclick' callback, or create a new callback route.

Sure. Should I take this up after #1672 or before ?

**Comment by hboon** [comment]
@JamesSmartCell bump
