### ISSUE TITLE
Redesign ERC721 to be align with recent ERC1155 update we made [ERC721]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2233]
The good news is, that we already made the layout for ERC1155, which now can be applied to the ERC721 redesign. Note, that unlike ERC1155, in the Assets tab you will not find the menu icon in the top right. Since there no way for multiple selection, I skipped it. 

**Zeplin:**
https://zpl.io/bzzgow7

![ERC721-android](https://user-images.githubusercontent.com/51817359/142425180-b31b52ef-30eb-4708-8866-19f2a93911ab.jpg)

Another Example is with FIFA tickets:
![ERC721-fifa-android](https://user-images.githubusercontent.com/51817359/142425683-c904c093-94b1-48f3-b5fd-225c4bcaced7.jpg)

https://zpl.io/agEY0nR

https://user-images.githubusercontent.com/51817359/142426556-8be43902-ea56-4741-b0c9-1f77eadca9db.mov

**Comment by JamesSmartCell** [comment]
Nice, this would be a great task for @justindg .

Just one clarification point, when you say 'Since there no way for multiple selection, I skipped it.' you're referring to ERC721 explicitly?

![screen1](https://user-images.githubusercontent.com/12689544/142782732-6ddba4b1-80a6-4f42-80ec-234252ce77d1.jpg)
![screen2](https://user-images.githubusercontent.com/12689544/142782739-9eec4a82-3c28-4072-a01b-8c4c4238c5f4.jpg)
![screen3](https://user-images.githubusercontent.com/12689544/142782765-772789ee-ec13-4737-8caf-fd3e6701de29.jpg)

Because we support this for ERC1155 (as per your original spec).

**Comment by hboon** [comment]
> Just one clarification point, when you say 'Since there no way for multiple selection, I skipped it.' you're referring to ERC721 explicitly?
> Because we support this for ERC1155 (as per your original spec).

Yes, this issue is only for ERC721; to make the UI for ERC721 look similar to ERC1155's.

**Comment by colourfreak** [comment]
What's the status of this? Who is working on this? Who manages this task? Shall we re-assign? @hboon

**Comment by justindg** [comment]
> What's the status of this? Who is working on this? Who manages this task? Shall we re-assign? @hboon

I have opened a pull request last month. Most of the work is done, and there are some minor issues that needed to be addressed first before we can merge. 

https://github.com/AlphaWallet/alpha-wallet-android/pull/2271
