### ISSUE TITLE
Can't import 12-words key and no message explaining why

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#2281]
Clicking "Import" button leads to nothing.

1. Import wallet
2. Type 12 keywords
3. Click "Import", nothing happens.

 If 12-words key is not supported, the button should gray out or give a reason why import doesn't work.

**Comment by JamesSmartCell** [comment]
This would be impossible to diagnose given the information. At the very least, give build version and #. Also what device are you using etc.

Suffice to say I just tested it on two phones, API24 and API30 both with different security and it's working correctly at my end.

Since this works correctly on all my devices can you try these:

1 - generate a seed phrase on a different phone (or the same and delete the wallet), then import. Does it work?
2 - Build the project and deploy, then test. Does it still fail?
3 - If 1. fails, it's the phone security setup, if 1. passes but your seed phrase fails then the seed phrase is bad - if this is the case we need to add an error that indicates what's happening.

**Comment by JamesSmartCell** [comment]
Closing as resolved outside of github.
