### ISSUE TITLE
Uniswap app does not connect to wallet on Android

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2303]
1. Open Browser 
2. Go to Uniswap
3. Notice that it does not inject web 3.0

**Comment by colourfreak** [comment]
![Screenshot_20220105-125347_AlphaWallet.jpg](https://user-images.githubusercontent.com/51817359/148214559-a3b2c5e6-a618-44a3-8849-2de863bd03b9.jpg)

**Comment by JamesSmartCell** [comment]
Yep, this is new. I guess they did another refactor. Does it still work on our iOS?

**Comment by hboon** [comment]
Got this far at least:

<img width="487" alt="Screenshot 2022-01-06 at 12 44 59 PM" src="https://user-images.githubusercontent.com/56189/148329517-03429d8b-3ace-4982-a9a8-d4bd03693f48.png">

**Comment by hieronymus4826** [comment]
> ![Screenshot_20220105-125347_AlphaWallet.jpg](https://user-images.githubusercontent.com/51817359/148214559-a3b2c5e6-a618-44a3-8849-2de863bd03b9.jpg)

This is because you are on Polygon in the browser and you have Selected Ethereum on Uniswap by default. If you switch one of the two you will connect.

**Comment by colourfreak** [comment]
![Screenshot_20220111-072847_AlphaWallet.jpg](https://user-images.githubusercontent.com/51817359/148892480-2e935f7b-6a89-4473-bf08-8a801d978081.jpg)

**Comment by JamesSmartCell** [comment]
This Twitter post from the Trust guys is relevant: 

https://twitter.com/vikmeup/status/1362467948489674754

@seabornlee has found a partial fix but it's not 100% reliable.

Also Quickswap is now broken, it used to work correctly - it looks like it shares source from Uniswap, so it being broken is expected if that's the case.

**Comment by seabornlee** [comment]
Found the reason. Solution will come soon.

**Comment by JamesSmartCell** [comment]
I have made a small update which mean we regain functionality for this and quickswap without needing to change provider. This should tide us over until we can update the provider.

**Comment by guangxingmao** [comment]
> I have made a small update which mean we regain functionality for this and quickswap without needing to change provider. This should tide us over until we can update the provider.

https://user-images.githubusercontent.com/19208420/150492207-782d52c7-46b2-46f3-b9a3-71b42f5871aa.mp4

hello,after merged,I find a new bug，it can't connect to wallet

Test Dapp https://etherscan.io/ 
Steps:
1.Choose Any contract 
2.Click Contract
3.Click Write Contract
4.Click Connect to Web3
5.Then click MetaMask 

Maybe Reason：
I see only "onPageStarted" method will evaluateJavascript, After step2, it only do "onPageFinished"  method,
and the url is https://cn.etherscan.com/token/0xdac17f958d2ee523a2206206994597c13d831ec7#writeContract.

<img width="1194" alt="截屏2022-01-18 21 52 22" src="https://user-images.githubusercontent.com/19208420/150494809-315c36d0-7ed4-4ac4-bf18-a97fe88c07f9.png">
It's a iframe!  so you need evaluateJavascript again before iframe init.

It works well after I reload page because it go "onPageStarted" method again, and evaluateJavascript again.
