### ISSUE TITLE
Migrate to Latest version of Dagger

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2321]
Currently we are stuck on Dagger 2.22 - the latest version (as this issue is written) is 2.35.1 / 2.28.3

To upgrade you can go through this tutorial, as above 2.22 Dagger changes quite a bit:

https://proandroiddev.com/getting-started-with-dagger-2-27-on-android-by-example-8534f468175

After this refactor, the injection code should look a little less complex, and the effort to add a new Activity should be slightly less.

Things to watch out for:

some ViewModels serve multiple activities, for example:

```
	@ActivityScope
	@ContributesAndroidInjector(modules = TokenFunctionModule.class)
	abstract TokenFunctionActivity bindTokenFunctionActivity();

	@ActivityScope
	@ContributesAndroidInjector(modules = TokenFunctionModule.class)
	abstract FunctionActivity bindFunctionActivity();

	@ActivityScope
	@ContributesAndroidInjector(modules = TokenFunctionModule.class)
	abstract TokenDetailActivity bindTokenDetailActivity();

	@ActivityScope
	@ContributesAndroidInjector(modules = TokenFunctionModule.class)
	abstract TokenActivity bindTokenActivity();
```

This may be quite a big project - if you encounter difficulties please let me know.

**Comment by asif-finimble** [comment]
@JamesSmartCell, we need to use dagger-hilt right?

**Comment by asif-finimble** [comment]
Task Update Jan 19, Wednesday:   
- Migrated Dagger-android 2.2 to Dagger-hilt 2.38.1.    
## Changes:   
- ```@Component, @ContributesAndroidInjector, ``` etc are removed.   
- ViewModelFactories are not required in Hilt as they are auto generated. Therefore all modules for providing dependencies for ViewModelFactories are combined to a single module called ```ViewModelModule```.   
- AppComponent is not required as ```@HiltAndroidApp``` generates it.    
- Unlike dagger, Hilt uses monolithic component system meaning all activities have components with same class definition, though the instances are different. More: https://dagger.dev/hilt/monolithic.html. Due to this we don't need to create separate modules for each activity. Any Module with ```@InstallIn(ActivityComponent.class)``` can provide dependencies to all activities.   
- For injection, all activities and fragments are annotated with ```@AndroidEntryPoint```. 
  - ViewModels are annotated with ```@HiltViewModel``` and ```@Inject``` on constructor.

**Comment by asif-finimble** [comment]
References, guides & tutorials used:   
- Migration guide: https://dagger.dev/hilt/migration-guide
- Baiscs: 
  - https://dagger.dev/hilt/quick-start.html   
  - https://dagger.dev/hilt/view-model.html  
  - https://developer.android.com/training/dependency-injection/hilt-android

**Comment by asif-finimble** [comment]
### Adding new Activity or Fragment  
- Annotate the Activity with ```@AndroidEntryPoint```.
- Annotate the field or constructor with ```@Inject``` for injecting dependencies. 
- Activities can access dependencies from modules with ```@InstallIn(SingletonComponent.class)``` &  ```@InstallIn(ActivityComponent.class)```.   
- Fragments can access dependencies from modules with ```@InstallIn(SingletonComponent.class)``` &  ```@InstallIn(FragmentComponent.class)```.  
   
  
### Injecting into ViewModels
- Annotate the ViewModel with ```@HiltViewModel```.    
- Annotate the field or constructor with ```@Inject```.    
- ViewModels can receive dependencies from Modules with ```@InstallIn(SingletonComponent.class)``` & ```@InstallIn(ViewModelComponent.class)```.   
- Define dependencies for ViewModels in ```ViewModelModule```.

**Comment by asif-finimble** [comment]
Task Update Jan 20:   
- Migration Done. Tested major screens. Working fine.   
- Pushed the Code.   


@JamesSmartCell can you please test it on your end and let me know if I should make any changes?

**Comment by JamesSmartCell** [comment]
Thanks, I'll check it

**Comment by asif-finimble** [comment]
> Thanks, I'll check it, it's this branch right:
> 
> https://github.com/AlphaWallet/alpha-wallet-android/tree/2321_migrate-dagger-to-latest

Yes.
