### ISSUE TITLE
Proguard rules are not provided

### ISSUE THREAD

**Issue by mik237** [AlphaWallet/alpha-wallet-android#2352]
When I set minifyEnabled true in gradle file for release build, it crashes. Please provide proper pro-guard rules for the code.

**Comment by JamesSmartCell** [comment]
@justindg @asif-finimble do either of you have experience editing proguard rules? If so can either of you educate me/the rest of us who don't. I have noticed minifyEnabled crashes too. I'm guessing we have to protect essential areas of the app from being removed by minify. It's like we're doing the job of the compiler, and you know they say never send a man to do a machine's job.

**Comment by asif-finimble** [comment]
Well proguard basically removes classes that are not used in code and most of the times I have faced problems & crashes when request/response DTOs are removed by proguard because we manually dont instantiate many DTOs - JSON parser does it. So proguard thinks that this class is not used. So we provide a rule to exclude the package that contains DTOs and proguard won't "minify" them and leave them as it is. Generally I put ```@Keep``` annotation on DTO classes which will prevent proguard from removing them.  We can also specify a rule for the same.      
In case of libraries used, they provide their own proguard rules.

**Comment by asif-finimble** [comment]
@JamesSmartCell should I take this up? I can try inspecting the crash and update proguard rules. Lets see what @justindg suggests.

**Comment by JamesSmartCell** [comment]
Hi @asif-finimble yes, can you look at this. I think there are a few classes that are stripped by minify that are needed for execution - probably library classes. We probably need to identify what these are are explicitly declare them as being needed. I wonder if we can specify a whole library at a go, then we can see where the problem is. I suspect it is either 'TrustWalletCore' or keys.c, which are the two native code processes.

**Comment by asif-finimble** [comment]
OK. I'll work on it after the current tickets are done.

**Comment by asif-finimble** [comment]
@JamesSmartCell I have added proguard rules based on tests and crashes. Added rules for TrustWallet library, entities, js interfaces etc. I tested send/receive payment, wallet connect, dappbrowser switch/add ethereum chain, and so far works as expected.  
Branch: https://github.com/AlphaWallet/alpha-wallet-android/tree/2352_proguard  

Can you test and let me know if changes are needed?
