### ISSUE TITLE
Ethereum mainnet's native token icon is used as Rinkeby native token icon

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2425]
Seems to happen after switching back from mainnet. The balance looks correct (i.e. it *is* Rinekby's). Something like:

1. Enable testnet
2. Pull down in Wallet tab
3. Enable mainnet
4. Pull down in Wallet tab
5. Enable testnet
6. Pull down in Wallet tab

The Ethereum mainnet's native token's icon (sometimes?) is shown:

<img width='200' src='https://user-images.githubusercontent.com/56189/155936630-ef985114-2b59-4ed7-b847-ffb9471a009c.jpg'>
<img width='200' src='https://user-images.githubusercontent.com/56189/155936645-15930dc7-dc72-434a-8233-c696724e17bb.jpg'>

**Comment by JamesSmartCell** [comment]
@justindg looks like we're seeing the fallback/default icon here. It could due to either an old process loading the wrong tokenIcon, or tokenIcon aborting.

Also, is this 0x007 ?? - be careful with having this wallet on your phone, don't accidentally send any eth to it, it's got sweep bots watching the balance.

**Comment by JamesSmartCell** [comment]
Either way, I wasn't able to reproduce it, you might have more luck.

**Comment by JamesSmartCell** [comment]
I have seen this now. Will attempt to fix.
