### ISSUE TITLE
cannot mint nft with  opensea with Rinkeby

### ISSUE THREAD

**Issue by HemangiVekaria** [AlphaWallet/alpha-wallet-android#2526]
I opened testnets.opensea.io in browser and connect to wallet using WalletConnect then click on create and it's opening page to create nft. I uploaded image there and set name of that NFT but cannot get any Collection in dropdown to choose. Is there any setting to get list of collection there? Without that it's throwing error. Can't create nft. 

With AlphaWallet it's working but i am doing same thing with my application DApp browser and also on chrome but cannot get a collection list. Can anyone help? I think there's some settings or anything?

![image](https://user-images.githubusercontent.com/17717369/161558732-b75670e6-a306-409e-ad25-34dfdb362a74.png)

**Comment by JamesSmartCell** [comment]
Hi again @HemangiVekaria, thanks for reporting this I'll check it.

**Comment by JamesSmartCell** [comment]
I think this is an issue with OpenSea, not AlphaWallet. I just tried creating an NFT and they mint it for you, they only need your address (provided via walletconnect).

I just minted this NFT - because I already had some deployed contract I just used the name from the existing contract:

https://testnets.opensea.io/assets/0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656/73301158607185938929634570134102981044984305286916549900884904066123407818753

If you would like to try this; I have a minting site that works with Rinkeby here:

https://jamessmartcell.github.io/

Just connect via WalletConnect, then mint either punks or apes depending on your preference. Once these have minted successfully and appear in the wallet, you can go back to OpenSea and you should have at least one entry in the collections tab which you can use.

**Comment by HemangiVekaria** [comment]
Thanks, @JamesSmartCell For help as always. I created a collection on my metamask and use that same account to connect via WalletConnect and now I can mint NFT from Opensea. Thanks again
