### ISSUE TITLE
Improve how we display Network in the ActionSheet

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2554]
This is how it looks now:
![2022-04-14 08 26 33](https://user-images.githubusercontent.com/51817359/163335274-66aba520-6580-4dd6-bcc2-563fe637d7b1.jpg)

Note that we indicate the network in the right corner of the Balance cell. Let's use another row. So below the "Balance" we will have one more row "Network". Then icon + Network name

<img width="1636" alt="Screenshot 2022-04-14 at 08 40 45" src="https://user-images.githubusercontent.com/51817359/163335488-d4079239-47f5-4b40-8d16-9643ca0aeece.png">

**Zeplin:**
https://zpl.io/dxD1PKL
https://zpl.io/awGoGOD (you can reuse this component, but ignore chevron)

**Comment by JamesSmartCell** [comment]
@colourfreak I made that change previously because on some Android form factors the ActionSheet becomes too big, especially when sending transactions. This is especially bad on the earlier Pixel phones where the ActionSheet overflows the display. I imagine it would also affect the newer Samsung Mini phones too.

Maybe what we can do is; follow the above design, sense if the ActionSheet will no longer fit into the page and then condense the network icon/name into the edge of the balance as previously (but with the black/white text as per the design above). This would only affect a small but still sizeable proportion of phones. If we go with that design the widget will need to be able to display in the horizontal or vertical alignment.

Alternatively our auto-scaling might compensate for this by now. That is another approach that might be better.

@justindg is more of an expert in this area than I am - what do you think?

**Comment by justindg** [comment]
Given the examples above, there seems to be enough space to fit, but I need to confirm this by testing on a variety of screen sizes

**Comment by justindg** [comment]
Right now when I expand all the widgets, the sheet goes all the way through the top, which looks fairly acceptable. What's missing is a scrollable area because some elements could be completely hidden.

**Comment by JamesSmartCell** [comment]
But, do we want to scroll or fit into the page?

**Comment by justindg** [comment]
I feel like it is inevitable to have scroll given the number of widgets that could be shown. Or we could also consider is limiting the number of widgets that could be displayed? If we try to fit dynamically it might cause inconsistency across devices, depending on how we implement it

**Comment by JamesSmartCell** [comment]
Yeah ok. I just don't like the ActionSheet needing to scroll to see all the data, since the data is quite critical and being able to see all of it at once makes you feel less likely to make a mistake.

If I can see all the data at once I get an instinctive feel that it's ok to press confirm and push the tx. If I couldn't see all the data I'd feel anxious.

**Comment by colourfreak** [comment]
Hmmm...

It will be 40pt higher. The whole-cell is 60pt. So we scale down the Balance cell in favor of the Network cell. 

<img width="977" alt="Screenshot 2022-04-15 at 09 43 52" src="https://user-images.githubusercontent.com/51817359/163541160-a6a346d5-6726-4248-b8f4-e14931ed5534.png">

**Comment by JamesSmartCell** [comment]
> Hmmm...
> 
> It will be 40pt higher. The whole-cell is 60pt. So we scale down the Balance cell in favor of the Network cell.
> 
> <img alt="Screenshot 2022-04-15 at 09 43 52" width="977" src="https://user-images.githubusercontent.com/51817359/163541160-a6a346d5-6726-4248-b8f4-e14931ed5534.png">

I like this solution - @justindg can you implement this update? I would prefer if you create a widget that only needs to be given the chainId and produces the view with the Icon and text to the side. Can you also make the widget able to display the text vertically underneath the icon too? I would re-use this component in a few other places.

**Comment by toanphamhd** [comment]
7add18328c01d95f78862ae5fc6025e2fd3b8588, thank you sirr

**Comment by justindg** [comment]
> Can you also make the widget able to display the text vertically underneath the icon too? I would re-use this component in a few other places.

@JamesSmartCell, can you point me to an existing use case? Would need to check if it's worth including in this particular widget, or if I should create an entirely new one. Thanks :)

**Comment by JamesSmartCell** [comment]
Yes, it's fine to create a new Widget, but you can incorporate TokenIcon/ChainName widgets in it. Kind of like a holding-widget.

It would also be used in the SwitchChain ActionSheet (but in vertical form).

**Comment by justindg** [comment]
> Yes, it's fine to create a new Widget, but you can incorporate TokenIcon/ChainName widgets in it. Kind of like a holding-widget.
> 
> It would also be used in the SwitchChain ActionSheet (but in vertical form).

Noted, will be doing this in a separate PR :) Currently working on it
