### ISSUE TITLE
scriptURI() and IPFS

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2785]
When using scriptURI() if the script is located in IPFS it is assumed to be certified.

See https://eips.ethereum.org/EIPS/eip-5169#security-considerations

Using IPFS, the script location fixes the script integrity,

**Comment by hboon** [comment]
What do we need to implement?

**Comment by JamesSmartCell** [comment]
The 'certified' lock, which shows whether the TokenScript is signed or not.

If the script if from IPFS then it has full integrity and is effectively signed (because of the hashing mechanics).

**Comment by hboon** [comment]
I see. So would you help me to understand how the ERC design works here? Is this correct:

It's effectively signed because if it's linked to IPFS, it means the deployer (or admin, depending on how the token contract is designed) has confirmed their trust for the script, aka there's a proper chain of trust. And if it's not IPFS, the script might have changed without them knowing?

**Comment by JamesSmartCell** [comment]
> I see. So would you help me to understand how the ERC design works here? Is this correct:
> 
> It's effectively signed because if it's linked to IPFS, it means the deployer (or admin, depending on how the token contract is designed) has confirmed their trust for the script, aka there's a proper chain of trust. And if it's not IPFS, the script might have changed without them knowing?

Yes, exactly. We can only guarantee it's the trusted TokenScript from just getScript() if the hash is signed by the contract owning key - which it effectively is using IPFS (or other hash linked storage system). You might need to use the IPFS hashing algorithm to re-verify the file stored locally if any other process is able to access it on the phone. On Android this only applies if the phone is rooted.
