### ISSUE TITLE
Create new magic link format and a new token-spawning message format

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#294]
To allow token encoded magic links from the organiser.

Can be something like this: 33 bytes is the token link after which you can shave of the first byte and use the remaining, if it is less than 33 bytes you know it is an index.

**Comment by JamesSmartCell** [comment]
Yes adding an extra leading byte is a good solution.

Further we should have a spec for the values used as in future we will have several types of magic link.

Since we now have two types of magic link the spec should be:

0x00: Standard Magic link
0x01: Spawnable magic link, calling spawnPassTo to create the token.

There will be several more types of magic link coming. Have this value in the leading byte so that byte parsers which interpret the bytes coming next.

Without the leading byte the parser will just interpret the link as a standard magic link to maintain backward compatibility.

I'll modify the source code in a branch on the token import library - this library is shared between all the java-using projects (Desktop tool, website magiclink server, Android alpha-wallet).

**Comment by James-Sangalli** [comment]
@JamesSmartCell wouldn't this break the old format for magic links?

**Comment by James-Sangalli** [comment]
@JamesSmartCell @colourful-land 

The idea is to have an extra byte before the price, a non zero value for this byte would represent the new format, an absence of this byte would represent the old format.

**Comment by James-Sangalli** [comment]
Check can be like this: 

    private static boolean isTokenIdFormat(byte[] linkBytes) 
    {
        return linkBytes[0] == 0x01;
    }

**Comment by JamesSmartCell** [comment]
Have a leading byte which is 0x01 -- 0xFF.
This will designate the type of link to follow.
If the leading byte is zero then it's a legacy magic link - because the magic link value will need to be 16 eth or greater to have a value in the top byte. We suspect there is no such magic link that is out there and still unclaimed.

So far:

0x01: Standard magic link.
0x02: Spawn token magic link.
0x03: Customisable spawn token link.

**Comment by JamesSmartCell** [comment]
So far it's working well. I have tested it with existing tokens and also a new customisable token spawning system I'm working on.

**Comment by colourful-land** [comment]
I think that magic-test† method will do for now and for a few years. I was a bit concerned over being too much deviated from W3C's `LinkedData` model, which requires the readable part of the thing readable, but I realised I can't do too much to satisfy everyone, since token ID wasn't designed to be readable by courtisy of early Ethereum rule-breakers.

† https://www.systutorials.com/docs/linux/man/5-magic/

**Comment by colourful-land** [comment]
Boon:

> The parser we are using in iOS doesn't have `textContent()` and the library we use requires us to pass in the function name and arg types (and return type) separately, but this format can be parsed, so it's not an issue.

Further, regarding return type:

> As long as we are prepared to include a way to explicitly specify a return type later, if necessary — which we should be able to, just use the implicit rules unless the return type is explicitly specified — this sounds good too. I haven't gone through the entire list of Solidity types, but there's a lingering thought that maybe something like the (Ethereum) `Address` or arrays might be an issue (or maybe not).
