### ISSUE TITLE
Difficulty Detecting and Adding ERC20 Tokens

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-android#3016]
Usually ERC20 (and hence DAI) token detection is quite reliable though. It ought to appear automatically if there's send/receive transactions involving it.

A user complained about not seeing the token DAI in Mainnet to add it. He typed in the token searcher but the page remained blank. I suggested enabling Mainnet...without result. 

I checked on my end and the token was there to enable in Populars Tokens but at times most of them disappeared from others testing in other addresses. 

Apart from this today it took to my wallet to detect all the tokens on chain more than an hour.  It could be and I think it was because of the bad internet connection that I am suffering these days here in Cuba...

**Comment by JamesSmartCell** [comment]
I believe this has been fixed - the reason was twofold - firstly the Google URL validator was being triggered by the API key which was preventing the transfer detector from working, secondly when the transfer detector was working the token wouldn't always get picked up correctly due to deviations from the ERC20 spec (which are filled in hindsight by Etherscan).

These have been fixed now, we will be having an official test channel soon but for now we'll have to wait for the updated release.

The release is on hold pending a high priority fix which is going in over the next couple of days.

**Comment by JamesSmartCell** [comment]
This should be now fixed in the 3.62 release.
