### ISSUE TITLE
USDC.e disappearing after adding + closing app

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#3045]
Contract: 0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664

**Comment by JamesSmartCell** [comment]
@seabornlee I have looked at this one; I get the opposite to the reported user, but it's not working as expected. 

It looks like this is what's happening for me:

1. Add the USDC.e Coin, Avalanche gets enabled as expected.
2. Go back to wallet page; USDC.e is not showing. 
3. Go to Add/Hide tokens, see that USDC.e is not enabled (as you would expect it to be). 
4. Enable USDC.e coin.
5. Go back to wallet page; USDC.e is still not showing.
6. Refresh tokens, USDC.e is now showing.
7. Restart app, USDC.e is showing.

I can see this can be fixed by a single mod - when user explicitly adds a token, it should be marked as enabled and user modified even if it's zero. The reason I added two visibility markers to tokens is so that users can explicitly enable zero balance tokens to be visible, but the default is to hide them (unless they are the base token, which is always shown if the chain is enabled).

I think I broke it recently, so I'll fix it.
