### ISSUE TITLE
Google Play Services Consulting

### ISSUE THREAD

**Issue by muchaartur** [AlphaWallet/alpha-wallet-android#3049]
Hello I would kindly ask about adding dependency and changing project file to push app to google play. I found in code this.

// WARNING! WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!
    // WARNING!  Don't add dependency on Google Play Services without consulting
    // WARNING!  The China marketing team
    // WARNING!  Many Chinese Android phones execute (meaning terminate) any app that
    // WARNING!  users google gms summarily, like immune systems cleansing infections
    // WARNING! WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!

Your advise would be highly appreciated. Thank you.

**Comment by JamesSmartCell** [comment]
Hi @muchaartur it's because we do a build for China, where Google services aren't permitted due to CCP policy. Some phone OS (like Huawei) detect if apps are attempting to use Google services (or if they are built with Google services libraries) and they may force terminate that app.

This warning is less relevant now, because we do separate builds for China/FSDroid which don't have any Google service libraries. If you go to 'Build Variants' in the AndroidStudio project you'll find the 'noAnalytics' project builds which build without those libraries.

I hope this helps!

**Comment by muchaartur** [comment]
thank you!
