### ISSUE TITLE
Update date query for repo server

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#314]
Repo server needs to be able to send an update date of XML files. Otherwise we're just burning through data each time the wallet starts checking for new token definition files.

**Comment by hboon** [comment]
Only need to return a `304` + send empty body if `If-Modified-Since` date in header is newer than the XML's timestamp:

> Include the IF-Modified-Since header HTTP header with the local XML's last modified date in the GET request. If the XML on the server has not been modified, a 304 will be returned with an empty body. Be careful with timezone! Put a bit of thinking cases like this: the user moves from timezone A to timezone B and missing a latest update for up to 24 hours.

From https://github.com/alpha-wallet/contracts/blob/master/README.md:

    curl -H "Accept: text/xml; charset=UTF-8" -H "IF-Modified-Since: Mon, 02 Jul 2018 13:23:00 GMT" -H "X-Client-Name: AlphaWallet" -H "X-Client-Version: 1.0.3" -H "X-Platform-Name: iOS" -H "X-Platform-Version: 11.1.2" https://repo.awallet.io/0xd8e5f58de3933e1e35f9c65eb72cb188674624f3

**Comment by JamesSmartCell** [comment]
@hboon : this doesn't appear to be working. After the Java tests I ran failed I tried the curl line you suggest and it always returns the full file, no matter what the comparison date is. It appears the server isn't returning the file date. I am guessing that iOS always loads the file at each startup. If we go with this we will be burning a lot of data. It's a minor issue at the moment, but can you check the iOS isn't re-loading at each check.

curl -H "Accept: text/xml; charset=UTF-8" -H "IF-Modified-Since: Mon, 02 Sep 2018 13:23:00 GMT" -H "X-Client-Name: AlphaWallet" -H "X-Client-Version: 1.0.3" -H "X-Platform-Name: iOS" -H "X-Platform-Version: 11.1.2" https://repo.awallet.io/0xd8e5f58de3933e1e35f9c65eb72cb188674624f3

**Comment by hboon** [comment]
@JamesSmartCell ah yes, I meant that the repo server has to be made to do this:

> Only need to return a 304 + send empty body if If-Modified-Since date in header is newer than the XML's timestamp:

So you can write the Android client to expect the above behavior and it'll just work when the server does return a `304` like described. (The server shouldn't return the file date though).

Sorry, I was vague. I wrote this comment right after reading your message on Telegram and had the context that this repo is for the server without realizing that this is also the Android app repo.

> I am guessing that iOS always loads the file at each startup. If we go with this we will be burning a lot of data.

Yes, iOS does this too. It's minor for now like you say. It's not that bad because we don't have many XMLs and only a launch (and not resume) and other specific actions triggers the download. Good to fix it though.

**Comment by JamesSmartCell** [comment]
OK that's fine then

**Comment by miang719** [comment]
@colourful-land waiting your action

**Comment by James-Sangalli** [comment]
@colourful-land believe this is handled now?

**Comment by James-Sangalli** [comment]
Solved with routing via 2019/xx etc
