### ISSUE TITLE
Lock/unlock or encrypt/decrypt the private key

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#365]
There should be some means to lock the private key, so it needs to be unlocked by the user each time it's used.

Determine which method is best, it could be one of these or a combination of (or something else):

- fingerprint unlock.
- pin entry.
- pattern unlock.
- password.

**Comment by hboon** [comment]
Relevant: https://github.com/AlphaWallet/alpha-wallet-ios/issues/721

**Comment by colourful-land** [comment]
@JamesSmartCell @James-Sangalli @hboon need to find out how Trust or imtoken did it for comparison.

**Comment by hboon** [comment]
@colourful-land 

Trust provides a user setting to enable Touch/Face ID/PIN. Once enabled, user has to authenticate themselves when the app is launched/switched to. It's just an app-level check like described in https://github.com/AlphaWallet/alpha-wallet-ios/issues/721#issuecomment-429268136:

```
result = callAppleAPIToShowTouchIDOrFaceID
if result == "authorized" {
    //yeah, user has proven himself, let user proceed to use the app
} else {
    //nope
}
```

We already have this feature. Let's call this (A).

imToken's app is not open source, their library at https://github.com/consenlabs/token-core-ios doesn't handle storing of the password used to encrypt the private key, so it's up to the app to handle it. I experimented with the app. Every time you want to sign a transaction, imToken prompts you to type in the password. The app also displays at various times that they can't recover the password. So at least by design, they don't store the password. They implement locking the entire app with (A) too.

For signing, we can add this in iOS: https://github.com/AlphaWallet/alpha-wallet-ios/issues/721#issuecomment-429887067 which is to let iOS add an additional level of protection for the password that is stored in the keychain. Everytime we access that password, we provide a string to describe what we are doing and iOS will automatically prompt the user with that descriptive string. Users have to auth before iOS releases the password to our app. Let's call this (B). We just have to make sure we don't hold on to the password in the app (which we don't at the moment).

We also have to decide if we implement (B): do we drop (A) or use the same setting to enable/disable both, or force (B) to always be enabled etc

**Comment by James-Sangalli** [comment]
This is done in keystore upgrade #785
