### ISSUE TITLE
Remove "My Wallet Address" in settings

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#487]
ios: https://github.com/AlphaWallet/alpha-wallet-ios/issues/978

1. It's not a setting.
2. It's already shown without going to Settings.

@farrahfazirah protest if you see it otherwise.

**Comment by farrahfazirah** [comment]
This is debatable. 

I believe **"My Wallet Address" should still remain under Settings** because:

1. There may be users used to accessing their wallet address through Settings.

2. The 'receive' feature does not necessarily fulfil accessibility to a user's wallet address.

The reason why we are implementing the send and receive feature is because it's a UX standard for wallets and necessary for mass adoption of DApps. However, it doesn't fulfil the UX of seeing a wallet address within one click of a button. It takes the user 2 clicks to get to their wallet address when the receive feature is implemented which is similar to having  "My Wallet Address" in the Settings.

For now, "My Wallet Address" should still remain in the settings. We will address the UX issue aforementioned in number 2 in the next phase of design.

**Comment by colourful-land** [comment]
Seems well thought.
