### ISSUE TITLE
Lose of precision in Transaction Details

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#674]
1. Send someone 0.01158ETH.
2. Wait for it confirmed.
3. It shows 0.0116 ETH is sent.
Example:
https://etherscan.io/tx/0x75dcafbb0bd04c5e3d925ba38ee734622112f35c3d8c87aee76d7a0e49094502

If you read the transaction detail you see that the amount is correct. However, because the UI displays a wrong number (rounded up), the user is forced into thinking this is the cause that the payment is not accepted (the real reason is that user needs to wait a bit more). This can be reproduced by trying to pay Windscribe VPN with crypto.

**Comment by hboon** [comment]
@colourful-land: in iOS, the Transactions tab shows "0.0115 ETH" (inconsistent!) and the detail screen shows the correct amount. It was rounded up/down presumably in the original codebase because there isn't enough space to show the precise amount.

What should it be shown as in the Transactions tab instead then?

@JamesSmartCell: a while back, when we were working on multi-chain, you suggested that we could display something like "0.0000xx ETH" verbatim to indicate tiny/dust Ether amounts that would otherwise be shown as "0 Ethereum (ETH)" or "0.0000 Ethereum (ETH)" in the Wallet tab. Do you remember what was the format you proposed?

**Comment by hboon** [comment]
> you suggested that we could display something like "0.0000xx ETH"

Oh, it's this format "~0.0000". https://github.com/AlphaWallet/alpha-wallet-ios/issues/1136.

So in this case "~0.0115" or "~0.0116"? Or is there a better way?

**Comment by JamesSmartCell** [comment]
Android was updated to round down. Now is matching iOS.
