### ISSUE TITLE
(BUG AlphaWallet  Current Version 2.01.0 ) the share option is not working properly 

### ISSUE THREAD

**Issue by friendsmobile** [AlphaWallet/alpha-wallet-android#754]
# Project Information

* Repository:  https://github.com/AlphaWallet/alpha-wallet-android
* Project Name:  AlphaWallet
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://play.google.com/store/apps/details?id=io.stormbird.wallet&hl=en_US

# Expected behavior

When I click on the share option, different types of social media applications should appear where I can share it.

# Actual behavior

When I click the share option, no response to the application appears

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=io.stormbird.wallet&hl=en_US)the application
*  open the application
* go to Browse tab 
* click the 3 vertical dots at top right 
* click on share option 
* Note the Error

* Browser/App version: Current Version 2.01.0
* Operating system: 6.0

#### Recording Of The Bug

![20190714_151322](https://user-images.githubusercontent.com/51118734/61182251-850fa680-a5e5-11e9-926a-510d660428f6.gif)

**Comment by JamesSmartCell** [comment]
Thanks, the issue here is that we aren't sharing anything because there's no webpage to share. One of two things could happen here: either the app removes the 'share' option if your dapp browser isn't pointing at any webpage, or when it's not pointed at anything it could share a message like 'I'm using Alphawallet'.
