### ISSUE TITLE
Display suggestions when importing long SEED phrase

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#976]
Please use Moonlight app (iOS) as a reference.

![Import_with_Seed_Android](https://user-images.githubusercontent.com/51817359/69209722-6c735680-0bac-11ea-8b08-3ca832ea1cf1.jpg)

**Comment by tomekalphawallet** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1568

**Comment by JamesSmartCell** [comment]
Yes we asked some ppl to come up with a UX for this previously - it will make a good project for external developer. I think there's enough info in the above picture for a developer to implement this. The suggestions would come from the valid word list which is part of the project anyway.

**Comment by JamesSmartCell** [comment]
This has been assigned as a task for external team.

**Comment by jzaki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1400] As a wallet user, I want to import my wallet's SEED phrase more readily, so that I'm not frustrated with typing long seed phrases](https://trello.com/c/b47sz01Q/31-1400-as-a-wallet-user-i-want-to-import-my-wallets-seed-phrase-more-readily-so-that-im-not-frustrated-with-typing-long-seed-phras)

**Comment by jzaki** [comment]
For posterity, the dictionary is just words from [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt)
